version: '3.5'

## docker run -d 
##        -e MYSQL_USER=mahendra 
##        -e MYSQL_PASSWORD=pass@1234 
##        -e MYSQL_DATABASE=sakila 
##             mahendrshinde/mysql-sample:sakila

volumes:
  data:
    driver: local
services:

  db:
    image: mahendrshinde/mysql-sample:sakila
    volumes:
    - data:/var/lib/mysql

    environment:
      - MYSQL_USER=mahendra
      - MYSQL_PASSWORD=pass@1234
      - MYSQL_DATABASE=sakila
    ports:
      - 3306