version: '3.5'

## docker run -d 
##        -e MYSQL_USER=mahendra 
##        -e MYSQL_PASSWORD=pass@1234 
##        -e MYSQL_DATABASE=sakila 
##             mahendrshinde/mysql-sample:sakila

services:
  db:
    image: mahendrshinde/mysql-sample:sakila
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: 500m
          memory: '256MB'
    environment:
      - MYSQL_USER=mahendra
      - MYSQL_PASSWORD=pass@1234
      - MYSQL_DATABASE=sakila
    ports:
      - 3306