apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    ## Mount the storage on MAXIMUM ONE Node in R/W
    - ReadWriteOnce 
    ## Other options: 
    ## 1. READONLYMANY
    ## 2. READWRITEONCE
    ## 3. READWRITEONCEPOD ## NEW ###
