apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-demo
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: claim1
      containers:
        - name: myapp1
          image: nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
