apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
spec:
  hostPath:
    path: /home/mahendra/data1/
  capacity:
    storage: 100Mi
  volumeMode: Filesystem  
  claimRef:
    name: claim1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
